# Generated by Django 2.2 on 2020-08-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора записи')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта автора записи')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст записи')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('redacted_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
